# Generated by Django 4.2.3 on 2023-07-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_authoritaire',
            field=models.BooleanField(default=False, verbose_name='Is authoritaire'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_client',
            field=models.BooleanField(default=False, verbose_name='Is client'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='username',
            field=models.CharField(default='default_username', max_length=100),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Role',
            field=models.CharField(choices=[('client', 'client'), ('authoritaire', 'authoritaire')], max_length=100),
        ),
    ]
