# Generated by Django 4.2.3 on 2023-07-08 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_userfile_user_alter_utilisateur_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='user',
        ),
    ]
