# Generated by Django 4.2.3 on 2023-07-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_userfile_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='files',
            field=models.ManyToManyField(related_name='clients', to='dashboard.userfile'),
        ),
    ]
