# Generated by Django 4.2.3 on 2023-07-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_utilisateur_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='userfile',
            name='clients',
            field=models.ManyToManyField(related_name='client_files', to='dashboard.utilisateur'),
        ),
        migrations.AddField(
            model_name='userfile',
            name='utilisateurs',
            field=models.ManyToManyField(related_name='user_files', to='dashboard.utilisateur'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='files',
            field=models.ManyToManyField(related_name='utilisateur', to='dashboard.userfile'),
        ),
    ]
